"""added relationships between quizzes and companies

Revision ID: 015c3719a631
Revises: 6a7f408b80ef
Create Date: 2025-11-27 19:02:06.217128

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "015c3719a631"
down_revision: Union[str, Sequence[str], None] = "6a7f408b80ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("quizzes", sa.Column("company_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "quizzes", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "quizzes", type_="foreignkey")
    op.drop_column("quizzes", "company_id")
    # ### end Alembic commands ###
