"""make name and password nullable

Revision ID: 08f63ea6d980
Revises: b3c8298d1943
Create Date: 2025-11-08 19:30:38.513322

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08f63ea6d980"
down_revision: Union[str, Sequence[str], None] = "b3c8298d1943"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=False)
